"""Initial models

Revision ID: 2c855bb83bd7
Revises: 
Create Date: 2025-04-26 23:35:13.740642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c855bb83bd7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draft_picks')
    op.drop_table('players')
    op.drop_table('teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('teams_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('position_needs', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='teams_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('players',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('players_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('college', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='players_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('draft_picks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pick_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('round', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('original_team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.id'], name='draft_picks_current_team_id_fkey'),
    sa.ForeignKeyConstraint(['original_team_id'], ['teams.id'], name='draft_picks_original_team_id_fkey'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='draft_picks_player_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='draft_picks_pkey')
    )
    # ### end Alembic commands ###
