"""Remove previous_team_id from draft_picks

Revision ID: 42b98b0787a2
Revises: 6f4ca59ca464
Create Date: 2025-07-16 16:07:30.811293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b98b0787a2'
down_revision: Union[str, None] = '6f4ca59ca464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('draft_picks_previous_team_id_fkey', 'draft_picks', type_='foreignkey')
    op.drop_column('draft_picks', 'previous_team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_picks', sa.Column('previous_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key('draft_picks_previous_team_id_fkey', 'draft_picks', 'teams', ['previous_team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
