"""Initial migration

Revision ID: 457c9fa2a45f
Revises: 
Create Date: 2025-04-28 00:52:59.559664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457c9fa2a45f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_drafts_id'), 'mock_drafts', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=False),
    sa.Column('college', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('qb', sa.Integer(), nullable=False),
    sa.Column('rb', sa.Integer(), nullable=False),
    sa.Column('wr', sa.Integer(), nullable=False),
    sa.Column('te', sa.Integer(), nullable=False),
    sa.Column('ot', sa.Integer(), nullable=False),
    sa.Column('iol', sa.Integer(), nullable=False),
    sa.Column('de', sa.Integer(), nullable=False),
    sa.Column('dt', sa.Integer(), nullable=False),
    sa.Column('lb', sa.Integer(), nullable=False),
    sa.Column('cb', sa.Integer(), nullable=False),
    sa.Column('s', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('draft_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pick_number', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('current_team_id', sa.Integer(), nullable=False),
    sa.Column('original_team_id', sa.Integer(), nullable=False),
    sa.Column('previous_team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['original_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['previous_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_picks_id'), 'draft_picks', ['id'], unique=False)
    op.create_table('mock_draft_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mock_draft_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('draft_pick_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draft_pick_id'], ['draft_picks.id'], ),
    sa.ForeignKeyConstraint(['mock_draft_id'], ['mock_drafts.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_draft_picks_id'), 'mock_draft_picks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mock_draft_picks_id'), table_name='mock_draft_picks')
    op.drop_table('mock_draft_picks')
    op.drop_index(op.f('ix_draft_picks_id'), table_name='draft_picks')
    op.drop_table('draft_picks')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_mock_drafts_id'), table_name='mock_drafts')
    op.drop_table('mock_drafts')
    # ### end Alembic commands ###
