"""Removed false nullable from player_id in Mock Draft Pick table.

Revision ID: 6dac9abd2be6
Revises: b826d5c637dd
Create Date: 2025-05-05 17:54:48.003761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dac9abd2be6'
down_revision: Union[str, None] = 'b826d5c637dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
