"""Made year field of Mock Drafts table not nullable.

Revision ID: 6f4ca59ca464
Revises: fe73960ce221
Create Date: 2025-05-09 19:48:10.225637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4ca59ca464'
down_revision: Union[str, None] = 'fe73960ce221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mock_drafts', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mock_drafts', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
