"""Added num_rounds to mock draft table.

Revision ID: 71004b788c03
Revises: 457c9fa2a45f
Create Date: 2025-05-03 11:23:06.777096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71004b788c03'
down_revision: Union[str, None] = '457c9fa2a45f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_drafts', sa.Column('num_rounds', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mock_drafts', 'num_rounds')
    # ### end Alembic commands ###
