"""Added num_rounds to mock draft table.

Revision ID: a79eccb4b812
Revises: 71004b788c03
Create Date: 2025-05-03 13:15:05.388691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79eccb4b812'
down_revision: Union[str, None] = '71004b788c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_controlled_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mock_draft_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mock_draft_id'], ['mock_drafts.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_controlled_teams_id'), 'user_controlled_teams', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_controlled_teams_id'), table_name='user_controlled_teams')
    op.drop_table('user_controlled_teams')
    # ### end Alembic commands ###
