"""Removed false nullable from player_id in Mock Draft Pick table.

Revision ID: b826d5c637dd
Revises: f0c8fefae488
Create Date: 2025-05-05 17:11:33.303275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b826d5c637dd'
down_revision: Union[str, None] = 'f0c8fefae488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mock_draft_picks', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mock_draft_picks', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
