"""Add original_team_id to mock_draft_picks

Revision ID: baf440654de3
Revises: 42b98b0787a2
Create Date: 2025-07-16 16:19:48.280260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baf440654de3'
down_revision: Union[str, None] = '42b98b0787a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_draft_picks', sa.Column('original_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key('mock_draft_picks_original_team_id_fkey', 'mock_draft_picks', 'teams', ['original_team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mock_draft_picks_original_team_id_fkey', 'mock_draft_picks', type='foreignkey')
    op.drop_column('mock_draft_picks', 'original_team_id')
    # ### end Alembic commands ###
