"""Added year field to Mock Drafts table.

Revision ID: fe73960ce221
Revises: 6dac9abd2be6
Create Date: 2025-05-09 19:44:31.491192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe73960ce221'
down_revision: Union[str, None] = '6dac9abd2be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_drafts', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mock_drafts', 'year')
    # ### end Alembic commands ###
